### PR TITLE
Add Zest Icons (free version)

### PR DESCRIPTION
**Pull request by candidexmedia**
[Library Source](https://zesticons.com/icons/?p=zest-free)

Please note: I'm having some issues with some of the icons in "Adventure", "Arrows", and "Brands". I've emailed Andrey from Penpot about it, but I believe it has something to do with "Transform to Path":

https://user-images.githubusercontent.com/95003834/209908067-d21cd1ee-1363-4097-80f0-c7e6936ef007.mp4

### CODE REVIEW

**Comment by superalex** [comment]
Thank you very much!

I think the problem is some imported svgs have the properties fill-rule and clip-rule set (those have the correct preview):



And some don't:



Are you importing all of them in the same way?

Regards,

**Comment by candideu** [comment]
> Are you importing all of them in the same way?

Yes, I imported them all from an .svg.

**Comment by candidexmedia** [comment]
> Are you importing all of them in the same way?

Yes, I imported them all from an .svg.

**Comment by candidexmedia** [comment]
I've added a group fill to the icons that were causing issues and updated the file: https://github.com/penpot/penpot-files/pull/23/commits/b54587d5b7fa25b1eda61ac4b6750aafc189b6f6

**Pull request merged**
